# Server
server:
  port: 8080

# Spring
spring:
  application:
    name: Web Demo
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/bootcamp
    username: root
    password: admin
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: collectionPool
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# Logging
logging:
  level:
    root: INFO
    org.springframework.boot: INFO

